###Register user
POST http://localhost:4004/register/User
Content-Type:application/json 

{   
    "userId": "Tirthendu",
    "userName": "tirthendu manna",
    "userEmail": "tirthendu.manna@sap.com",
    "userPhone": "9876543212",
    "sellerFlag": true,
    "buyerFlag": true
}
### get User
GET http://localhost:4004/admin/User
### delete User

DELETE http://localhost:4004/admin/User(3)